# Generated by Django 6.0 on 2025-12-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_sql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='descripition',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
