# Generated by Django 6.0 on 2026-01-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_sql', '0002_task_descripition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='descripition',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
