# Generated by Django 6.0.1 on 2026-01-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_sql', '0006_alter_task_options_task_assigned_to_task_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название награды')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cost', models.IntegerField(default=100, verbose_name='Стоимость (XP)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
            },
        ),
    ]
