# Generated by Django 6.0.1 on 2026-01-28 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_sql', '0007_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_at_purchase', models.IntegerField(default=100, verbose_name='Стоимость (XP)')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время покупки')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo_sql.reward', verbose_name='Купленная награда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
