# Generated by Django 6.0.1 on 2026-02-04 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_sql', '0008_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Заработано XP')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_sql.task', verbose_name='Выполненный квест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выполнение квеста',
                'verbose_name_plural': 'Выполнения квестов',
                'ordering': ['-completion_date'],
            },
        ),
    ]
