# Generated by Django 6.0.1 on 2026-02-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_sql', '0010_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
    ]
