# Generated by Django 6.0.1 on 2026-02-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_sql', '0012_family_chatmessage_family_reward_family_task_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
    ]
