# Generated by Django 6.0.1 on 2026-02-27 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_sql', '0013_remove_task_assigned_to_remove_task_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo_sql.task', verbose_name='Выполненный квест'),
        ),
    ]
