# Generated by Django 6.0.1 on 2026-03-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_sql', '0014_alter_taskcompletion_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
